name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --strict-peer-dependencies

      - name: Build library
        run: pnpm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build documentation site
        run: |
          # Change to docs directory and install dependencies
          cd docs
          pnpm install --no-frozen-lockfile

          # Copy README.md to public directory so it can be fetched
          mkdir -p public
          # Create a main README from the package information
          echo "# Fjell Lib" > public/README.md
          echo "" >> public/README.md
          echo "Server-side Library for Fjell - A powerful TypeScript data operations and business logic system." >> public/README.md
          echo "" >> public/README.md
          echo "## Installation" >> public/README.md
          echo "" >> public/README.md
          echo "\`\`\`bash" >> public/README.md
          echo "npm install @fjell/lib" >> public/README.md
          echo "\`\`\`" >> public/README.md
          echo "" >> public/README.md
          echo "## Quick Start" >> public/README.md
          echo "" >> public/README.md
          echo "\`\`\`typescript" >> public/README.md
          echo "import { createRegistry, createLibrary } from '@fjell/lib'" >> public/README.md
          echo "" >> public/README.md
          echo "// Create a registry for your data models" >> public/README.md
          echo "const registry = createRegistry('business-models')" >> public/README.md
          echo "" >> public/README.md
          echo "// Create a library instance for your data model" >> public/README.md
          echo "const userLibrary = createLibrary(" >> public/README.md
          echo "  registry," >> public/README.md
          echo "  { keyType: 'user' }," >> public/README.md
          echo "  userOperations," >> public/README.md
          echo "  userOptions" >> public/README.md
          echo ")" >> public/README.md
          echo "" >> public/README.md
          echo "// Perform data operations" >> public/README.md
          echo "const user = await userLibrary.operations.create({" >> public/README.md
          echo "  name: 'Alice Johnson'," >> public/README.md
          echo "  email: 'alice@example.com'" >> public/README.md
          echo "})" >> public/README.md
          echo "" >> public/README.md
          echo "const users = await userLibrary.operations.all({})" >> public/README.md
          echo "\`\`\`" >> public/README.md

          # Copy examples README as examples-README.md
          cp ../examples/README.md public/examples-README.md

          # Copy example files to public directory
          mkdir -p public/examples
          cp ../examples/*.ts public/examples/

          # Copy RELEASE_NOTES.md for architecture section
          cp ../RELEASE_NOTES.md public/ 2>/dev/null || echo "# Release Notes" > public/RELEASE_NOTES.md

          # Copy package.json so version can be fetched
          cp ../package.json public/

          # Build the Vite documentation site
          pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
